### ISSUE TITLE
array_map(): An error occurred while invoking the map callback

### ISSUE THREAD

**Issue by JanPetterMG** [oscarotero/Embed#226]
URL: http://www.autofil.no/
Demo: https://oscarotero.com/embed3/demo/index.php?url=http%3A%2F%2Fwww.autofil.no%2F

Not sure what the problem is, but Embed gets redirected to `http://` as a result of the following warning:
```
Warning:  array_map(): An error occurred while invoking the map callback in /vendor/embed/embed/src/Adapters/Adapter.php on line 647

Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Malformed URL: http://' in /vendor/embed/embed/src/Http/Url.php:654
Stack trace:
#0 /vendor/embed/embed/src/Http/Url.php(518): Embed\Http\Url::parse('http://')
#1 /vendor/embed/embed/src/Http/Url.php(33): Embed\Http\Url-&gt;parseUrl('http://')
#2 /vendor/embed/embed/src/Http/Url.php(23): Embed\Http\Url-&gt;__construct('http://')
#3 /vendor/embed/embed/src/Adapters/Adapter.php(307): Embed\Http\Url::create('http://')
#4 [internal function]: Embed\Adapters\Adapter-&gt;Embed\Adapters\{closure}(Object(Embed\Providers\OpenGraph))
#5 /vendor/embed/embed/src/Adapters/Adapter.php(647): array_map(Object(Closure), Array)
#6 /vendor/embed/embed/src/Adapters/Adapter.php(312): Embed\Adapters\Adapter-&gt;getFirstFromProviders(Object(Closure), 'http://www.auto...')
#7 /vendor/embed/embed/src/Adapters/Adapter.php(93): Embed\Adapters\Adapter-&gt;getUrl()
#8 /vendor/embed/embed in /vendor/embed/embed/src/Http/Url.php on line 654
```

**Comment by oscarotero** [comment]
The problem was that `og:url` contains `http://`. I've fixed ignoring these malformed urls.
