### ISSUE TITLE
Github Error

### ISSUE THREAD

**Issue by realodix** [oscarotero/Embed#375]
https://github.com/oscarotero/Embed/blob/master/composer.json

https://oscarotero.com/embed/demo/index.php?url=https%3A%2F%2Fgithub.com%2Foscarotero%2FEmbed%2Fblob%2Fmaster%2Fcomposer.json

```php
Fatal error: Uncaught TypeError: Return value of Embed\Adapters\Github\Detectors\Code::fallback() must be
an instance of Embed\EmbedCode or null, none returned in
/var/www/oscarotero.com/www/embed/src/Adapters/Github/Detectors/Code.php:44 
Stack trace: #0 /var/www/oscarotero.com/www/embed/src/Adapters/Github/Detectors/Code.php(16): 
Embed\Adapters\Github\Detectors\Code->fallback() 
#1 /var/www/oscarotero.com/www/embed/src/Detectors/Detector.php(23): Embed\Adapters\Github\Detectors\Code->detect() 
#2 /var/www/oscarotero.com/www/embed/src/Extractor.php(114): Embed\Detectors\Detector->get() 
#3 /var/www/oscarotero.com/www/embed/demo/index.php(209): Embed\Extractor->__get() 
#4 {main} thrown in /var/www/oscarotero.com/www/embed/src/Adapters/Github/Detectors/Code.php on line 44
```

**Comment by oscarotero** [comment]
Fixed in 4.2.5. Thanks for notify
